INFO     core.jenkins_utils:jenkins_utils.py:210 running cleanup
DEBUG    urllib3.connectionpool:connectionpool.py:241 Starting new HTTP connection (1): localhost:8080
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 403 None
DEBUG    core.jenkins_utils:jenkins_utils.py:92 failed to get page on the first try, retrying after login
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /login?from=%2F HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /j_spring_security_check HTTP/1.1" 302 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /me/my-views/view/all/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /manage/securityRealm/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /computer/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /manage/credentials/store/system/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /submitDescription HTTP/1.1" 302 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /me/my-views/view/all/submitDescription HTTP/1.1" 302 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /me/my-views/view/all/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /user/admin/appearance/configSubmit HTTP/1.1" 200 134
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /user/admin/security/ HTTP/1.1" 200 None
DEBUG    conftest:conftest.py:88 Argument --remote-allow-origins=* added to the chrome
DEBUG    conftest:conftest.py:88 Argument --disable-gpu added to the chrome
DEBUG    conftest:conftest.py:88 Argument --no-sandbox added to the chrome
DEBUG    conftest:conftest.py:88 Argument --disable-dev-shm-usage added to the chrome
DEBUG    conftest:conftest.py:88 Argument --headless=new added to the chrome
DEBUG    conftest:conftest.py:88 Argument --window-size=1920,1080 added to the chrome
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:101 Selenium Manager binary found at: /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:114 Executing process: /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --language-binding python --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Found chromedriver 137.0.7151.68 in PATH: /usr/bin/chromedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chrome detected at /usr/bin/google-chrome
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Running command: /usr/bin/google-chrome --version
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Output: "Google Chrome 137.0.7151.68 "
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Detected browser: chrome 137.0.7151.68
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Required driver: chromedriver 137.0.7151.70
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Driver path: /usr/bin/chromedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Browser path: /usr/bin/google-chrome
DEBUG    selenium.webdriver.common.service:service.py:231 Started executable: `/usr/bin/chromedriver` in a child process with pid: 20938 using 0 to output -3
DEBUG    urllib3.connectionpool:connectionpool.py:241 Starting new HTTP connection (1): localhost:38229
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element/f.672F697B49DC053D8FC3EB7A28083B13.d.45449926AF8E68A9E8C262F84E714086.e.1/value HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element/f.672F697B49DC053D8FC3EB7A28083B13.d.45449926AF8E68A9E8C262F84E714086.e.3/value HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element/f.672F697B49DC053D8FC3EB7A28083B13.d.45449926AF8E68A9E8C262F84E714086.e.9/click HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/cookie HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:241 Starting new HTTP connection (1): localhost:8080
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /crumbIssuer/api/json HTTP/1.1" 200 155
DEBUG    core.jenkins_utils:jenkins_utils.py:31 update_crumb: 9308ad9de0d1a39b76137fc298460643e6a9427a1f8a9418425a0ec6723caa4d
DEBUG    LoginPage:login_page.py:32 login crumb: 9308ad9de0d1a39b76137fc298460643e6a9427a1f8a9418425a0ec6723caa4d
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/window HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/execute/sync HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/window/handles HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/window/handles HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/window HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/title HTTP/1.1" 200 0
DEBUG    Header:ui_element.py:69 Click on locator ('xpath', '//a[@href="/logout"]')
DEBUG    Header:ui_element.py:28 waiting for element_to_be_clickable(('xpath', '//a[@href="/logout"]'),)
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/execute/sync HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/element/f.6EDBE13A9C1CABF1DDD183145B56E942.d.225B31A56D4AEAA620CCD26A97C60D1B.e.56/enabled HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element/f.6EDBE13A9C1CABF1DDD183145B56E942.d.225B31A56D4AEAA620CCD26A97C60D1B.e.56/click HTTP/1.1" 200 0
DEBUG    LoginPage:ui_element.py:28 waiting for text_to_be_present_in_element(('xpath', '//main//h1'), 'Sign in to Jenkins')
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/element/f.6EDBE13A9C1CABF1DDD183145B56E942.d.408C023E4928AD612BCEF575D6AD2884.e.8/text HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/window HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "POST /session/c8ddd2eb0fb4c4e92792614812d990a2/refresh HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "GET /session/c8ddd2eb0fb4c4e92792614812d990a2/title HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:38229 "DELETE /session/c8ddd2eb0fb4c4e92792614812d990a2 HTTP/1.1" 200 0