INFO     core.jenkins_utils:jenkins_utils.py:210 running cleanup
DEBUG    urllib3.connectionpool:connectionpool.py:241 Starting new HTTP connection (1): localhost:8080
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 403 None
DEBUG    core.jenkins_utils:jenkins_utils.py:92 failed to get page on the first try, retrying after login
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /login?from=%2F HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /j_spring_security_check HTTP/1.1" 302 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /me/my-views/view/all/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /manage/securityRealm/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /computer/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /manage/credentials/store/system/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /submitDescription HTTP/1.1" 302 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /me/my-views/view/all/submitDescription HTTP/1.1" 302 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /me/my-views/view/all/ HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "POST /user/admin/appearance/configSubmit HTTP/1.1" 200 134
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /user/admin/security/ HTTP/1.1" 200 None
DEBUG    conftest:conftest.py:88 Argument --remote-allow-origins=* added to the chrome
DEBUG    conftest:conftest.py:88 Argument --disable-gpu added to the chrome
DEBUG    conftest:conftest.py:88 Argument --no-sandbox added to the chrome
DEBUG    conftest:conftest.py:88 Argument --disable-dev-shm-usage added to the chrome
DEBUG    conftest:conftest.py:88 Argument --headless=new added to the chrome
DEBUG    conftest:conftest.py:88 Argument --window-size=1920,1080 added to the chrome
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:101 Selenium Manager binary found at: /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:114 Executing process: /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --language-binding python --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Found chromedriver 137.0.7151.68 in PATH: /usr/bin/chromedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chrome detected at /usr/bin/google-chrome
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Running command: /usr/bin/google-chrome --version
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Output: "Google Chrome 137.0.7151.68 "
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Detected browser: chrome 137.0.7151.68
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Required driver: chromedriver 137.0.7151.70
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Driver path: /usr/bin/chromedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Browser path: /usr/bin/google-chrome
DEBUG    selenium.webdriver.common.service:service.py:231 Started executable: `/usr/bin/chromedriver` in a child process with pid: 10734 using 0 to output -3
DEBUG    urllib3.connectionpool:connectionpool.py:241 Starting new HTTP connection (1): localhost:39499
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element/f.B40C47CA4D9C01263206257DA10A8A93.d.93B201D1BFBF19E6D8A4E89D584468C9.e.2/value HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element/f.B40C47CA4D9C01263206257DA10A8A93.d.93B201D1BFBF19E6D8A4E89D584468C9.e.3/value HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element/f.B40C47CA4D9C01263206257DA10A8A93.d.93B201D1BFBF19E6D8A4E89D584468C9.e.6/click HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/cookie HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:241 Starting new HTTP connection (1): localhost:8080
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:8080 "GET /crumbIssuer/api/json HTTP/1.1" 200 156
DEBUG    core.jenkins_utils:jenkins_utils.py:31 update_crumb: a02786a3cb0239d89445d461bbe4421d9b0c818320ba20b8b660869d65136a2b
DEBUG    LoginPage:login_page.py:32 login crumb: a02786a3cb0239d89445d461bbe4421d9b0c818320ba20b8b660869d65136a2b
DEBUG    MainPage:ui_element.py:59 Click on locator ('link text', 'Manage Jenkins')
DEBUG    MainPage:ui_element.py:28 waiting for element_to_be_clickable(('link text', 'Manage Jenkins'),)
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/execute/sync HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/element/f.B40C47CA4D9C01263206257DA10A8A93.d.E7996B2E5C55C7747D0F61DA245F12A5.e.61/enabled HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element/f.B40C47CA4D9C01263206257DA10A8A93.d.E7996B2E5C55C7747D0F61DA245F12A5.e.61/click HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/url HTTP/1.1" 200 0
DEBUG    ManageJenkinsPage:ui_element.py:59 Click on locator ('xpath', "//a[@href='load-statistics']/..")
DEBUG    ManageJenkinsPage:ui_element.py:28 waiting for element_to_be_clickable(('xpath', "//a[@href='load-statistics']/.."),)
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/execute/sync HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/element/f.B40C47CA4D9C01263206257DA10A8A93.d.9961311FF7E962D5C9C5BBAFB2CD82D3.e.78/enabled HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "POST /session/a31f101142f197583dc6bf915dd9fef4/element/f.B40C47CA4D9C01263206257DA10A8A93.d.9961311FF7E962D5C9C5BBAFB2CD82D3.e.78/click HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/url HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "GET /session/a31f101142f197583dc6bf915dd9fef4/title HTTP/1.1" 200 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:39499 "DELETE /session/a31f101142f197583dc6bf915dd9fef4 HTTP/1.1" 200 0